/* STUDENTS:  DO NOT EDIT THIS FILE.  INSTEAD, MODIFY YOUR OWN PROJECT
 * CODE TO FIT THE SPECIFICATION GIVEN BY THE TESTS IN THIS FILE.
 *
 * If you DO modify it, we overwrite it with a fresh version from our repo
 * when grading, so you can't use it to fudge the tests anyway.
 *
 * This file is used by the CS3081W auto-grading system.
 *
 * Please note, the assessment tests for grading, will use the same include
 * files, class names, and function names for accessing students' code that you
 * find in this file.  So students, if you write your code so that it passes
 * these feedback tests, you can be assured that the auto-grader will at least
 * be able to properly link with your code.
 */

/*******************************************************************************
 * Includes
 ******************************************************************************/
#include <gtest/gtest.h>
#include "src/arena.h"
#include "src/arena_params.h"
#include "src/entity_type.h"

#ifdef ROBOT_TESTS

class RobotTest : public ::testing::Test {

 protected:
  virtual void SetUp() {
    // Initialize Arena for Collections of TESTS
    csci3081::arena_params aparams;
    arena = new csci3081::Arena(&aparams);
    robot = arena->robot();
  }
  csci3081::Arena * arena;
  csci3081::Robot * robot;
};

/*******************************************************************************
 * Test Cases
 ******************************************************************************/

TEST_F(RobotTest, RobotStopOnLightCollision) {
  robot->IncreaseSpeed();
  robot->set_position(200, 200);
  for(auto& ent : arena->get_entities()) {
    if(ent->get_type() == csci3081::kLight) {
      ent->set_position(201, 200);
      break;
    }
  }
  arena->AdvanceTime(1);
  arena->AdvanceTime(1);
  csci3081::WheelVelocity v = robot->get_motion_handler().get_velocity();
  EXPECT_EQ(std::make_tuple(v.left, v.right), std::make_tuple(0, 0)) << "Fail: Robot did not stop on collision with an Light";
};

TEST_F(RobotTest, DecreaseSpeedMin) {
  robot->DecreaseSpeed();
  csci3081::WheelVelocity v = robot->get_motion_handler().get_velocity();
  EXPECT_EQ(std::make_tuple(v.left, v.right), std::make_tuple(0, 0));
};

TEST_F(RobotTest, IncreaseSpeedMax) {
  int nIncrease = 10;
  while(nIncrease--)
    robot->IncreaseSpeed();
  csci3081::WheelVelocity v = robot->get_motion_handler().get_velocity();
  EXPECT_EQ(std::make_tuple(v.left, v.right),
            std::make_tuple(ROBOT_MAX_SPEED, ROBOT_MAX_SPEED));
  robot->IncreaseSpeed();
  v = robot->get_motion_handler().get_velocity();
  EXPECT_EQ(std::make_tuple(v.left, v.right),
            std::make_tuple(ROBOT_MAX_SPEED, ROBOT_MAX_SPEED));
};

#endif /* ROBOT_TESTS */
